hw7-2:simple_int_set_main.o
	g++ -o simple_int_set simple_int_set_main.o simple_int_set.cc -std=c++11
simple_int_set_main.o:simple_int_set_main.cc
	g++ -c simple_int_set_main.cc
clean:
	rm simple_int_set_main.o

