hw10-2:print_shape_main.o clock_time_main.o
	g++ -std=c++11 -o print_shape print_shape_main.o print_shape.cc
	g++ -std=c++11 -o clock_time clock_time_main.o clock_time.cc
print_shape_main.o:print_shape_main.cc
	g++ -c print_shape_main.cc
clock_time_main.o:clock_time_main.cc
	g++ -c clock_time_main.cc
clean:
	rm print_shape_main.o clock_time_main.o
