hw3-2: score_graph.o print_point.o array_2dim.o
	g++ -o score_graph score_graph.o
	g++ -o print_point print_point.o
	g++ -o array_2dim array_2dim.o
score_graph.o:score_graph.cc
	g++ -c score_graph.cc
print_point.o:print_point.cc
	g++ -c print_point.cc
array_2dim.o:array_2dim.cc
	g++ -c array_2dim.cc
clean:
	rm score_graph.o print_point.o array_2dim.o
