hw8-1:number_main.o rectangle_main.o
	g++ -o number number_main.o number.cc
	g++ -o rectangle rectangle_main.o rectangle.cc
number_main.o:number_main.cc
	g++ -c number_main.cc
rectangle_main.o:rectangle_main.cc
	g++ -c rectangle_main.cc
clean:
	rm number_main.o rectangle_main.o
