#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from cminus.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 7 "cminus.y"

#define YYPARSER /* distinguishes Yacc output from other code files */

#include "globals.h"
#include "util.h"
#include "scan.h"
#include "parse.h"

#define YYSTYPE TreeNode *
static char * savedName; /* for use in assignments */
static int savedLineNo;  /* ditto */
static TreeNode * savedTree; /* stores syntax tree for later return */
static int yylex(void); // added 11/2/11 to ensure no conflict with lex


#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	IF	258
#define	ELSE	259
#define	WHILE	260
#define	RETURN	261
#define	INT	262
#define	VOID	263
#define	END	264
#define	ID	265
#define	NUM	266
#define	ASSIGN	267
#define	EQ	268
#define	NE	269
#define	LT	270
#define	LE	271
#define	GT	272
#define	GE	273
#define	PLUS	274
#define	MINUS	275
#define	TIMES	276
#define	OVER	277
#define	LPAREN	278
#define	RPAREN	279
#define	LBRACE	280
#define	RBRACE	281
#define	LCURLY	282
#define	RCURLY	283
#define	SEMI	284
#define	COMMA	285
#define	ERROR	286


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int IF;
static const int ELSE;
static const int WHILE;
static const int RETURN;
static const int INT;
static const int VOID;
static const int END;
static const int ID;
static const int NUM;
static const int ASSIGN;
static const int EQ;
static const int NE;
static const int LT;
static const int LE;
static const int GT;
static const int GE;
static const int PLUS;
static const int MINUS;
static const int TIMES;
static const int OVER;
static const int LPAREN;
static const int RPAREN;
static const int LBRACE;
static const int RBRACE;
static const int LCURLY;
static const int RCURLY;
static const int SEMI;
static const int COMMA;
static const int ERROR;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,IF=258
	,ELSE=259
	,WHILE=260
	,RETURN=261
	,INT=262
	,VOID=263
	,END=264
	,ID=265
	,NUM=266
	,ASSIGN=267
	,EQ=268
	,NE=269
	,LT=270
	,LE=271
	,GT=272
	,GE=273
	,PLUS=274
	,MINUS=275
	,TIMES=276
	,OVER=277
	,LPAREN=278
	,RPAREN=279
	,LBRACE=280
	,RBRACE=281
	,LCURLY=282
	,RCURLY=283
	,SEMI=284
	,COMMA=285
	,ERROR=286


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::IF=258;
const int YY_parse_CLASS::ELSE=259;
const int YY_parse_CLASS::WHILE=260;
const int YY_parse_CLASS::RETURN=261;
const int YY_parse_CLASS::INT=262;
const int YY_parse_CLASS::VOID=263;
const int YY_parse_CLASS::END=264;
const int YY_parse_CLASS::ID=265;
const int YY_parse_CLASS::NUM=266;
const int YY_parse_CLASS::ASSIGN=267;
const int YY_parse_CLASS::EQ=268;
const int YY_parse_CLASS::NE=269;
const int YY_parse_CLASS::LT=270;
const int YY_parse_CLASS::LE=271;
const int YY_parse_CLASS::GT=272;
const int YY_parse_CLASS::GE=273;
const int YY_parse_CLASS::PLUS=274;
const int YY_parse_CLASS::MINUS=275;
const int YY_parse_CLASS::TIMES=276;
const int YY_parse_CLASS::OVER=277;
const int YY_parse_CLASS::LPAREN=278;
const int YY_parse_CLASS::RPAREN=279;
const int YY_parse_CLASS::LBRACE=280;
const int YY_parse_CLASS::RBRACE=281;
const int YY_parse_CLASS::LCURLY=282;
const int YY_parse_CLASS::RCURLY=283;
const int YY_parse_CLASS::SEMI=284;
const int YY_parse_CLASS::COMMA=285;
const int YY_parse_CLASS::ERROR=286;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		113
#define	YYFLAG		-32768
#define	YYNTBASE	32

#define YYTRANSLATE(x) ((unsigned)(x) <= 286 ? yytranslate[x] : 65)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     5,     7,     9,    11,    12,    17,    18,    19,
    28,    30,    32,    33,    41,    43,    45,    49,    51,    54,
    55,    61,    66,    69,    70,    73,    74,    76,    78,    80,
    82,    84,    87,    89,    95,   103,   109,   112,   116,   120,
   122,   124,   125,   131,   135,   139,   143,   147,   151,   155,
   157,   161,   165,   167,   171,   175,   177,   181,   183,   185,
   187,   188,   194,   196,   197,   201
};

static const short yyrhs[] = {    33,
     0,    33,    34,     0,    34,     0,    35,     0,    40,     0,
     0,    39,    10,    36,    29,     0,     0,     0,    39,    10,
    37,    25,    11,    38,    26,    29,     0,     7,     0,     8,
     0,     0,    39,    10,    41,    23,    42,    24,    46,     0,
    43,     0,     8,     0,    43,    30,    44,     0,    44,     0,
    39,    10,     0,     0,    39,    10,    45,    25,    26,     0,
    27,    47,    48,    28,     0,    47,    35,     0,     0,    48,
    49,     0,     0,    50,     0,    46,     0,    51,     0,    52,
     0,    53,     0,    54,    29,     0,    29,     0,     3,    23,
    54,    24,    49,     0,     3,    23,    54,    24,    49,     4,
    49,     0,     5,    23,    54,    24,    49,     0,     6,    29,
     0,     6,    54,    29,     0,    55,    12,    54,     0,    57,
     0,    10,     0,     0,    10,    56,    25,    54,    26,     0,
    58,    16,    58,     0,    58,    15,    58,     0,    58,    17,
    58,     0,    58,    18,    58,     0,    58,    14,    58,     0,
    58,    13,    58,     0,    58,     0,    58,    19,    59,     0,
    58,    20,    59,     0,    59,     0,    59,    21,    60,     0,
    59,    22,    60,     0,    60,     0,    23,    54,    24,     0,
    55,     0,    61,     0,    11,     0,     0,    10,    62,    23,
    63,    24,     0,    64,     0,     0,    64,    30,    54,     0,
    54,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    30,    34,    44,    47,    48,    51,    58,    61,    68,    73,
    75,    78,    81,    88,    97,    98,   102,   112,   114,   121,
   126,   133,   140,   150,   152,   162,   164,   165,   166,   167,
   168,   170,   170,   172,   176,   183,   188,   189,   193,   198,
   200,   207,   212,   216,   222,   228,   234,   240,   246,   252,
   254,   259,   264,   267,   272,   277,   279,   280,   281,   282,
   287,   292,   297,   298,   300,   309
};

static const char * const yytname[] = {   "$","error","$illegal.","IF","ELSE",
"WHILE","RETURN","INT","VOID","END","ID","NUM","ASSIGN","EQ","NE","LT","LE",
"GT","GE","PLUS","MINUS","TIMES","OVER","LPAREN","RPAREN","LBRACE","RBRACE",
"LCURLY","RCURLY","SEMI","COMMA","ERROR","program","declaration_list","declaration",
"var_declaration","@1","@2","@3","type_specifier","fun_declaration","@4","params",
"param_list","param","@5","compound_stmt","local_declarations","statement_list",
"statement","expression_stmt","selection_stmt","iteration_stmt","return_stmt",
"expression","var","@6","simple_expression","additive_expression","term","factor",
"call","@7","args","arg_list",""
};
#endif

static const short yyr1[] = {     0,
    32,    33,    33,    34,    34,    36,    35,    37,    38,    35,
    39,    39,    41,    40,    42,    42,    43,    43,    44,    45,
    44,    46,    47,    47,    48,    48,    49,    49,    49,    49,
    49,    50,    50,    51,    51,    52,    53,    53,    54,    54,
    55,    56,    55,    57,    57,    57,    57,    57,    57,    57,
    58,    58,    58,    59,    59,    59,    60,    60,    60,    60,
    62,    61,    63,    63,    64,    64
};

static const short yyr2[] = {     0,
     1,     2,     1,     1,     1,     0,     4,     0,     0,     8,
     1,     1,     0,     7,     1,     1,     3,     1,     2,     0,
     5,     4,     2,     0,     2,     0,     1,     1,     1,     1,
     1,     2,     1,     5,     7,     5,     2,     3,     3,     1,
     1,     0,     5,     3,     3,     3,     3,     3,     3,     1,
     3,     3,     1,     3,     3,     1,     3,     1,     1,     1,
     0,     5,     1,     0,     3,     1
};

static const short yydefact[] = {     0,
    11,    12,     1,     3,     4,     0,     5,     2,     6,     0,
     0,     0,     7,     0,     0,     9,    12,     0,     0,    15,
    18,     0,    19,     0,     0,     0,     0,    24,    14,    17,
    10,     0,    26,    21,    23,     0,     0,     6,     0,     0,
     0,    41,    60,     0,    22,    33,    28,    25,    27,    29,
    30,    31,     0,    58,    40,    50,    53,    56,    59,     0,
     0,    37,     0,     0,     0,     0,    32,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    38,     0,    64,    57,    39,    58,    49,    48,    45,    44,
    46,    47,    51,    52,    54,    55,     0,     0,     0,    66,
     0,    63,    34,    36,    43,    62,     0,     0,    65,    35,
     0,     0,     0
};

static const short yydefgoto[] = {   111,
     3,     4,     5,    10,    11,    22,     6,     7,    12,    19,
    20,    21,    27,    47,    33,    37,    48,    49,    50,    51,
    52,    53,    54,    64,    55,    56,    57,    58,    59,    65,
   101,   102
};

static const short yypact[] = {    -6,
-32768,-32768,    -6,-32768,-32768,    -1,-32768,-32768,   -15,   -16,
    -7,    20,-32768,    22,    18,-32768,    23,    39,    31,    35,
-32768,    57,    61,    62,    -6,    63,    65,-32768,-32768,-32768,
-32768,    67,    -6,-32768,-32768,    81,     1,    69,    72,    73,
    21,    14,-32768,    25,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,    68,    86,-32768,    44,    30,-32768,-32768,    25,
    25,-32768,    70,    75,    78,    79,-32768,    25,    25,    25,
    25,    25,    25,    25,    25,    25,    25,    25,    80,    82,
-32768,    25,    25,-32768,-32768,-32768,    34,    34,    34,    34,
    34,    34,    30,    30,-32768,-32768,    11,    11,    76,-32768,
    83,    84,   101,-32768,-32768,-32768,    25,    11,-32768,-32768,
   108,   109,-32768
};

static const short yypgoto[] = {-32768,
-32768,   107,    85,-32768,-32768,-32768,   -10,-32768,-32768,-32768,
-32768,    87,-32768,    89,-32768,-32768,   -52,-32768,-32768,-32768,
-32768,   -41,    -2,-32768,-32768,     8,     9,    10,-32768,-32768,
-32768,-32768
};


#define	YYLAST		118


static const short yytable[] = {    63,
     1,     2,    66,    39,    18,    40,    41,   -13,     9,    -8,
    42,    43,    13,    39,    18,    40,    41,    14,    79,    80,
    42,    43,    36,    44,     1,    17,    85,    28,    45,    46,
    42,    43,    16,    44,    42,    43,   -61,    28,   -42,    46,
    99,   100,    15,    44,   103,   104,   -16,    44,    23,    62,
    77,    78,    75,    76,    24,   110,    69,    70,    71,    72,
    73,    74,    75,    76,    25,   109,    86,    86,    86,    86,
    86,    86,    86,    86,    86,    86,    87,    88,    89,    90,
    91,    92,    26,    93,    94,   -20,    95,    96,    28,    32,
    38,    31,    34,    -8,    60,    61,    67,    68,    81,    82,
    83,   105,    84,    97,   108,    98,   106,   112,   113,     8,
     0,    30,    29,   107,     0,     0,     0,    35
};

static const short yycheck[] = {    41,
     7,     8,    44,     3,    15,     5,     6,    23,    10,    25,
    10,    11,    29,     3,    25,     5,     6,    25,    60,    61,
    10,    11,    33,    23,     7,     8,    68,    27,    28,    29,
    10,    11,    11,    23,    10,    11,    23,    27,    25,    29,
    82,    83,    23,    23,    97,    98,    24,    23,    10,    29,
    21,    22,    19,    20,    24,   108,    13,    14,    15,    16,
    17,    18,    19,    20,    30,   107,    69,    70,    71,    72,
    73,    74,    75,    76,    77,    78,    69,    70,    71,    72,
    73,    74,    26,    75,    76,    25,    77,    78,    27,    25,
    10,    29,    26,    25,    23,    23,    29,    12,    29,    25,
    23,    26,    24,    24,     4,    24,    24,     0,     0,     3,
    -1,    25,    24,    30,    -1,    -1,    -1,    33
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 31 "cminus.y"
{ savedTree = yyvsp[0];;
    break;}
case 2:
#line 35 "cminus.y"
{
				YYSTYPE t = yyvsp[-1];
				if (t != NULL){
					while(t->sibling != NULL)
						t = t->sibling;
					t->sibling = yyvsp[0];
					yyval = yyvsp[-1]; }
				else yyval = yyvsp[0];
			;
    break;}
case 3:
#line 44 "cminus.y"
{yyval = yyvsp[0];;
    break;}
case 4:
#line 47 "cminus.y"
{ yyval = yyvsp[0]; ;
    break;}
case 5:
#line 48 "cminus.y"
{ yyval = yyvsp[0]; ;
    break;}
case 6:
#line 51 "cminus.y"
{
				    savedName = copyString(previousToken);
				    savedLineNo = lineno;
				    yyval = newExpNode(VarDeK);
				    yyval->attr.name = savedName;
				    yyval->lineno = savedLineNo;
				    ;
    break;}
case 7:
#line 58 "cminus.y"
{	yyval = yyvsp[-1];
			yyval->child[0] = yyvsp[-3];
		;
    break;}
case 8:
#line 61 "cminus.y"
{
				   savedName = copyString(previousToken);
				   savedLineNo = lineno; 
				   yyval = newExpNode(VarDeK);
				   yyval->attr.name = savedName;
				   yyval->lineno = savedLineNo;
			     	 ;
    break;}
case 9:
#line 68 "cminus.y"
{savedName = copyString(tokenString);
			    yyval = yyvsp[-2]; 
			    yyval->child[0] = yyvsp[-4];
			    yyval->child[1] = newExpNode(ConstK);
			    yyval->child[1]->attr.val = atoi(savedName); 
			;
    break;}
case 10:
#line 73 "cminus.y"
{yyval = yyvsp[-5];;
    break;}
case 11:
#line 75 "cminus.y"
{yyval = newExpNode(TypeK);
	       	      yyval->attr.type = "int";
	     	;
    break;}
case 12:
#line 78 "cminus.y"
{yyval = newExpNode(TypeK);
			yyval->attr.type = "void";;
    break;}
case 13:
#line 81 "cminus.y"
{
		  savedName = copyString(previousToken);
		  savedLineNo = lineno;
		  yyval = newExpNode(FunDeK);
		  yyval->attr.name = savedName;
		  yyval->lineno = savedLineNo;
		;
    break;}
case 14:
#line 89 "cminus.y"
{	
			  yyval = yyvsp[-4];
			  yyval->child[0] = yyvsp[-6];
			  yyval->child[1] = yyvsp[-2];
			  yyval->child[2] = yyvsp[0]; 		  
			;
    break;}
case 15:
#line 97 "cminus.y"
{yyval = yyvsp[0]; ;
    break;}
case 16:
#line 98 "cminus.y"
{ yyval = newExpNode(SingleParaK);
		yyval->child[0] = newExpNode(TypeK);
		yyval->child[0]->attr.type = "void";;
    break;}
case 17:
#line 103 "cminus.y"
{
		  YYSTYPE t = yyvsp[-2];
		  if (t != NULL){
			while(t->sibling != NULL)
			  t = t->sibling;
			t->sibling = yyvsp[0];
			yyval = yyvsp[-2]; }
		  else yyval = yyvsp[0];
		;
    break;}
case 18:
#line 112 "cminus.y"
{yyval = yyvsp[0]; ;
    break;}
case 19:
#line 114 "cminus.y"
{
      			   savedName = copyString(previousToken);
     			   savedLineNo = lineno; 
			   yyval = newExpNode(SingleParaK);
			   yyval->child[0] = yyvsp[-1]; 
			   yyval->attr.name = savedName;
			   yyval->lineno = savedLineNo;;
    break;}
case 20:
#line 121 "cminus.y"
{savedName = copyString(previousToken);
			savedLineNo = lineno;
			yyval = newExpNode(ArrParaK);
			yyval->attr.name = savedName;
			yyval->lineno = savedLineNo;;
    break;}
case 21:
#line 126 "cminus.y"
{
			yyval = yyvsp[-2];
			yyval->child[0] = yyvsp[-4];
			yyval->attr.name = savedName;
			yyval->lineno = savedLineNo;;
    break;}
case 22:
#line 134 "cminus.y"
{
		 yyval = newStmtNode(CompoundK);
		 yyval->child[0] = yyvsp[-2];
		 yyval->child[1] = yyvsp[-1];
		;
    break;}
case 23:
#line 141 "cminus.y"
{
			  YYSTYPE t = yyvsp[-1];
			  if(t != NULL){
				while(t->sibling != NULL)
				  t = t->sibling;
			  	t->sibling = yyvsp[0];
			 	 yyval = yyvsp[-1]; }
			  else yyval = yyvsp[0]; 
			;
    break;}
case 24:
#line 150 "cminus.y"
{yyval= NULL;;
    break;}
case 25:
#line 153 "cminus.y"
{
		  YYSTYPE t = yyvsp[-1];
		  if(t != NULL){
			while(t->sibling != NULL)
			  t = t->sibling;
			t->sibling = yyvsp[0];
			yyval = yyvsp[-1]; }
		  else yyval = yyvsp[0];
		;
    break;}
case 26:
#line 162 "cminus.y"
{yyval = NULL;;
    break;}
case 27:
#line 164 "cminus.y"
{yyval = yyvsp[0]; ;
    break;}
case 28:
#line 165 "cminus.y"
{yyval = yyvsp[0]; ;
    break;}
case 29:
#line 166 "cminus.y"
{yyval = yyvsp[0]; ;
    break;}
case 30:
#line 167 "cminus.y"
{yyval = yyvsp[0]; ;
    break;}
case 31:
#line 168 "cminus.y"
{yyval = yyvsp[0]; ;
    break;}
case 32:
#line 170 "cminus.y"
{yyval = yyvsp[-1]; ;
    break;}
case 33:
#line 170 "cminus.y"
{;
    break;}
case 34:
#line 172 "cminus.y"
{
	       		yyval = newStmtNode(IfK);
			yyval->child[0] = yyvsp[-2];
			yyval->child[1] = yyvsp[0];;
    break;}
case 35:
#line 176 "cminus.y"
{
			yyval = newStmtNode(IfThenK);
			yyval->child[0] = yyvsp[-4];
			yyval->child[1] = yyvsp[-2];
			yyval->child[2] = yyvsp[0];
		;
    break;}
case 36:
#line 183 "cminus.y"
{
	       		yyval = newStmtNode(IterK);
			yyval->child[0] = yyvsp[-2];
			yyval->child[1] = yyvsp[0];;
    break;}
case 37:
#line 188 "cminus.y"
{;
    break;}
case 38:
#line 189 "cminus.y"
{
		yyval = newStmtNode(ReturnK);
		yyval->child[0] = yyvsp[-1];;
    break;}
case 39:
#line 193 "cminus.y"
{
	   yyval = newStmtNode(AssignK);
	   yyval->child[0] = yyvsp[-2];
	   yyval->child[1] = yyvsp[0];
	   yyval->attr.op = ASSIGN; ;
    break;}
case 40:
#line 198 "cminus.y"
{yyval = yyvsp[0];;
    break;}
case 41:
#line 200 "cminus.y"
{
    	savedName = copyString(previousToken);
	savedLineNo = lineno;
	yyval = newExpNode(IdK);
	yyval->lineno = savedLineNo;
	yyval->attr.name = savedName;
;
    break;}
case 42:
#line 207 "cminus.y"
{savedName = copyString(previousToken);
	savedLineNo = lineno;
	yyval = newExpNode(IdK);
	yyval->attr.name = savedName;
	yyval->lineno = savedLineNo;
	;
    break;}
case 43:
#line 212 "cminus.y"
{
	yyval = yyvsp[-3];
	yyval->child[0] = yyvsp[-1];;
    break;}
case 44:
#line 216 "cminus.y"
{
		  	yyval = newExpNode(OpK);
			yyval->child[0] = yyvsp[-2];
			yyval->child[1] = yyvsp[0];
			yyval->attr.op = LE;
		  ;
    break;}
case 45:
#line 222 "cminus.y"
{
			yyval = newExpNode(OpK);
			yyval->child[0] = yyvsp[-2];
			yyval->child[1] = yyvsp[0];
			yyval->attr.op = LT;
		  ;
    break;}
case 46:
#line 228 "cminus.y"
{
		  	yyval = newExpNode(OpK);
			yyval->child[0] = yyvsp[-2];
			yyval->child[1] = yyvsp[0];
			yyval->attr.op = GT;
		  ;
    break;}
case 47:
#line 234 "cminus.y"
{
			yyval = newExpNode(OpK);
			yyval->child[0] = yyvsp[-2];
			yyval->child[1] = yyvsp[0];
			yyval->attr.op = GE;
		  ;
    break;}
case 48:
#line 240 "cminus.y"
{
		  	yyval = newExpNode(OpK);
			yyval->child[0] = yyvsp[-2];
			yyval->child[1] = yyvsp[0];
			yyval->attr.op = NE;
		  ;
    break;}
case 49:
#line 246 "cminus.y"
{
			yyval = newExpNode(OpK);
			yyval->child[0] = yyvsp[-2];
			yyval->child[1] = yyvsp[0];
			yyval->attr.op = EQ;
		  ;
    break;}
case 50:
#line 252 "cminus.y"
{yyval = yyvsp[0];;
    break;}
case 51:
#line 254 "cminus.y"
{
		    	yyval = newExpNode(OpK);
			yyval->child[0] = yyvsp[-2];
			yyval->child[1] = yyvsp[0];
			yyval->attr.op = PLUS;;
    break;}
case 52:
#line 259 "cminus.y"
{
		    	yyval = newExpNode(OpK);
			yyval->child[0] = yyvsp[-2];
			yyval->child[1] = yyvsp[0];
			yyval->attr.op = MINUS;;
    break;}
case 53:
#line 264 "cminus.y"
{yyval = yyvsp[0];;
    break;}
case 54:
#line 267 "cminus.y"
{
			yyval = newExpNode(OpK);
			yyval->child[0] = yyvsp[-2];
			yyval->child[1] = yyvsp[0];
			yyval->attr.op = TIMES;;
    break;}
case 55:
#line 272 "cminus.y"
{
		    	yyval = newExpNode(OpK);
			yyval->child[0] = yyvsp[-2];
			yyval->child[1] = yyvsp[0];
			yyval->attr.op = OVER;;
    break;}
case 56:
#line 277 "cminus.y"
{yyval = yyvsp[0];;
    break;}
case 57:
#line 279 "cminus.y"
{yyval = yyvsp[-1];;
    break;}
case 58:
#line 280 "cminus.y"
{yyval = yyvsp[0];;
    break;}
case 59:
#line 281 "cminus.y"
{yyval = yyvsp[0];;
    break;}
case 60:
#line 282 "cminus.y"
{
		yyval = newExpNode(ConstK);
		yyval->attr.val = atoi(tokenString);
	;
    break;}
case 61:
#line 287 "cminus.y"
{savedName = copyString(previousToken);
     	  savedLineNo = lineno;
	  yyval = newExpNode(CallK);
	  yyval->attr.name = savedName;
	  yyval->lineno = savedLineNo;;
    break;}
case 62:
#line 292 "cminus.y"
{
     	yyval = yyvsp[-3];
	yyval->child[0] = yyvsp[-1];
     ;
    break;}
case 63:
#line 297 "cminus.y"
{ yyval = yyvsp[0]; ;
    break;}
case 64:
#line 298 "cminus.y"
{yyval = NULL;;
    break;}
case 65:
#line 300 "cminus.y"
{
	 	YYSTYPE t = yyvsp[-2];
		if(t!=NULL){
		  while(t->sibling != NULL)
			t = t->sibling;
		  t->sibling = yyvsp[0];
		  yyval = yyvsp[-2];}
		else yyval = yyvsp[0]; 
	 ;
    break;}
case 66:
#line 309 "cminus.y"
{yyval = yyvsp[0]; ;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 311 "cminus.y"


int yyerror(char * message)
{ fprintf(listing,"Syntax error at line %d: %s\n",lineno,message);
  fprintf(listing,"Current token: ");
  printToken(yychar,tokenString);
  Error = TRUE;
  return 0;
}

/* yylex calls getToken to make Yacc/Bison output
 * compatible with ealier versions of the CMINUS scanner
 */
static int yylex(void)
{ return getToken(); }

TreeNode * parse(void)
{ yyparse();
  return savedTree;
}

