hw3-3:touch_points.o cal_complex.o
	g++ -o touch_points touch_points.o
	g++ -o cal_complex cal_complex.o
touch_points.o:touch_points.cc
	g++ -c touch_points.cc
cal_complex.o:cal_complex.cc
	g++ -c cal_complex.cc
clean:
	rm touch_points cal_complex
